version: '3'

volumes:
  pg_auth_data:
    name: pg_auth_data

services:
  api:
    container_name: auth_api_service
    build:
      context: app
      dockerfile: settings/docker/fastapi/dockerfile
    env_file:
      app/.env
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 10s
    depends_on:
      - redis
      - postgres
      - nginx

  redis:
    container_name: auth_redis_cache
    build:
      context: app
      dockerfile: settings/docker/redis/dockerfile
    env_file:
      app/.env

  postgres:
    container_name: auth_postgres
    build:
      context: app/settings/docker/postgres
      dockerfile: dockerfile
    volumes:
      - pg_auth_data:/var/lib/postgresql/data/
    env_file:
      app/.env
    expose:
      - "5432"    
  
  nginx:
    container_name: nginx_auth_api
    restart: always
    image: nginx:1.19.2
    volumes:
      - ./app/settings/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/settings/docker/nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
    ports:
      - "81:80"



networks:
  default:
      name: auth_network